### PR TITLE
Virtual funding for RPS

### PR DESCRIPTION
**Pull request by kerzhner**
https://github.com/statechannels/monorepo/pull/742 should precede this PR. 

Also, integration tests are failing on this PR.

### CODE REVIEW

**Comment by lalexgap** [comment]
> Also, integration tests are failing on this PR. 

This is caused by the fact that we don't have a `hub` running when running the `integration-test`s and we're now trying to do `VirtualFunding`. I think I can make a quick change so that the strategy is an .env variable, so we can keep the `integration-test`s running with ledger funding for now.

**Comment by kerzhner** [comment]
I think that's a solid idea. Would be good to get this work merged in quickly so that others can start playing around with virtual funding and discovering remaining issues.

**Comment by lalexgap** [comment]
> I think that's a solid idea. Would be good to get this work merged in quickly so that others can start playing around with virtual funding and discovering remaining issues.

Updated here aa42884aa7f565ef142f0a23fac0a02c6a7ff386

**Comment by geoknee** [comment]
I confirmed this worked on my machine 🌋 .

**Pull request merged**
