### PR TITLE
Remove apps

### PR DESCRIPTION
**Pull request by andrewgordstewart**
When we get the apps monorepo running where we want it, we can pull this bandaid!

Getting things to work required many iterations of `yarn && yarn build`, since dev dependencies used by `xstate-wallet` were not specified in its `package.json` file.

### CODE REVIEW

**Comment by snario** [comment]
My hope was to get a ✅ on CircleCI on `apps` and then do this

**Comment by geoknee** [comment]
Does this remove `simple-hub`? Should it?

**Comment by andrewgordstewart** [comment]
> Does this remove `simple-hub`? Should it?

It does not. Maybe it should! Should I?

**Comment by geoknee** [comment]
Well, I spotted it over in the apps repo. So unless there is something I am misunderstanding, it should go. Could be done in a separate PR, though.

**Comment by snario** [comment]
Yes, `simple-hub` should only be in `apps`.

**Pull request merged**
