### PR TITLE
[nitro-protocol, devtools] Remove unused dependencies

### PR DESCRIPTION
**Pull request by geoknee**
We really want to be rid of `scrypt`. 

On master: 
```
➜  monorepo git:(master) yarn why scrypt
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "scrypt"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "scrypt@6.0.3"
info Reasons this module exists
   - "_project_#@statechannels#nitro-protocol#ganache-core#ethereumjs-wallet#scrypt.js" depends on it
   - Hoisted from "_project_#@statechannels#nitro-protocol#ganache-core#ethereumjs-wallet#scrypt.js#scrypt"
✨  Done in 6.61s.
```

On this branch: 
```
➜  monorepo git:(george/upgrade-devtools-deps) ✗ yarn why scrypt
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "scrypt"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 7.66s.
```

### CODE REVIEW

**Comment by snario** [comment]
Didn't know about `yarn why`, cool.

**Comment by geoknee** [comment]
Yeah it is useful, but not perfect. We would still have an issue if doing a fresh install https://github.com/LimeChain/etherlime/issues/314 , I think we are only avoiding it somehow due to our `yarn.lock` file.

**Comment by geoknee** [comment]
Or rather, this is what saves us: https://github.com/statechannels/monorepo/blob/9e0f3401b4ca6f85bc264b867b03c07eac9f5379/package.json#L34

We should push this resolution down into any packages that we publish.

**Comment by geoknee** [comment]
#2269

**Pull request merged**
