### PR TITLE
[monorepo] Include build-storybook in build:ci

### PR DESCRIPTION
**Pull request by geoknee**
Motivation: save developer time by preventing us from breaking storybook

TODO Fix all of the broken storybooks

I ran into this issue in `web3torrent`:
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/73

(start-storybook works, build-storybook does not)

### CODE REVIEW

**Comment by kerzhner** [comment]
Will be superseded by https://github.com/statechannels/monorepo/pull/1405

**Comment by spersico** [comment]
@geoknee is this still active or we can close it?

**Comment by kerzhner** [comment]
FYI, storybook is not functional at the moment: https://github.com/statechannels/monorepo/issues/1481

**Comment by snario** [comment]
@geoknee What's the situation here?

**Pull request closed without merging**
