### PR TITLE
Bizarre experimental changes to cancel test to get it to pass

### PR DESCRIPTION
**Pull request by snario**
Got 10 tests in a row passing locally... trying on CI

### CODE REVIEW

**Comment by snario** [comment]
Noticed this:
https://30220-209829093-gh.circle-artifacts.com/0/tmp/seed-download-cancel.pino.log
```
{"time":1590417603679,"level":30,"jsonRpcResponse":{"id":38,"jsonrpc":"2.0","error":{"code":300,"message":"Not your turn"}},"msg":"OUTGOING JSONRPC REQUEST:","name":"xstate-wallet","browserId":1}
```

**Comment by snario** [comment]
@spersico is it possible there is a race condition between when `getLatestPaymentReceipt` resolves and `closeChannel` is called? For example, `getLatestPaymentReceipt` returns and then the channel is updated by a regular `makePayment` and then `closeChannel` is called despite it not being that user's turn yet?

**Comment by andrewgordstewart** [comment]
> Noticed this:
> https://30220-209829093-gh.circle-artifacts.com/0/tmp/seed-download-cancel.pino.log
> 
> ```json
> {
>    "time":1590417603679,
>    "level":30,
>    "jsonRpcResponse":{
>       "id":38,
>       "jsonrpc":"2.0",
>       "error":{
>          "code":300,
>          "message":"Not your turn"
>       }
>    },
>    "msg":"OUTGOING JSONRPC REQUEST:",
>    "name":"xstate-wallet",
>    "browserId":1
> }
> ```

Should the `ChannelClient` reject when it gets this error response?

**Comment by snario** [comment]
I think it should

**Comment by snario** [comment]
> could it be that tests started passing with this change because the catch statement swallows the error instead of bubbling it up?

I don't think so, because the test failed again.

**Comment by snario** [comment]
It seems like this surface [some kind of error](https://github.com/statechannels/monorepo/pull/1963#issuecomment-633620371) so I'm going to close this PR in favour of us fixing that error.

**Pull request closed without merging**
