### PR TITLE
[wallet] Replace steps with a progress bar

### PR DESCRIPTION
**Pull request by geoknee**
progressbar

### CODE REVIEW

**Comment by geoknee** [comment]
Will wait for feedback on this idea before polishing up

- [ ] colors
- [ ] renaming

**Comment by snario** [comment]
To be honest I kind of like the step-by-step UI as it lets you inspect what's happening a bit more easily and get a sense for the process being undergone.

**Comment by geoknee** [comment]
The rationale is this: in the happy case, many screens / steps flick by very quickly making it pretty well impossible to track what is going on. When something is broken, or you are waiting on something, IMHO it seems best to focus on a particular message describing what is happening now, and not all the things that got successfully done or are yet to be attempted.

**Comment by geoknee** [comment]
Current UI for reference: 
old
(It doesn't seem quite right anyways. I guess the whole UI needs an overhaul)

**Comment by snario** [comment]
I can understand that rationale, makes sense

**Comment by geoknee** [comment]
Closing since I put this idea into the x-state wallet instead #938 .

**Pull request closed without merging**
