### PR TITLE
Update gitignore for logs

### PR DESCRIPTION
**Pull request by cf19drofxots**

### CODE REVIEW

**Comment by snario** [comment]
I think there are already `.gitignore` files inside the sub packages

**Comment by cf19drofxots** [comment]
There are, and I actually put this inside the `.gitignore` file of the `wallet` package, but seems like it's applicable for all packages unless for some reason we want to track local logs for some packages?

**Comment by snario** [comment]
I would put it inside the local `.gitignore` since it is the only one that produces files like this as of now

**Comment by cf19drofxots** [comment]
AFAICT the same script is used by the `devtools` package, so any package using `devtools` will end up producing these files as well, rendering the global coverage more useful, but I digress for now.

**Pull request merged**
