### PR TITLE
[web3torrent] UI Improvements

### PR DESCRIPTION
**Pull request by snario**
Screen Shot 2020-05-22 at 07 32 30

### CODE REVIEW

**Comment by geoknee** [comment]
Like
- new Data column
- horizntal alignment

Dislike
- hard to quickly pick out upload vs downloading channels
- sent / received terminology collides with payment terminology. I send you money, you send me data. prefer uploaded / downloaded
- disconnected (bad) is a grey dot. finished (good) is a different grey dot
- vertical alignment does a bit of a wave

Neutral
- blockies now have similar colour to rest of page. I think i preferred the contrast of having some blue -- it' was also statechannel blue, showing that this is part of the UX owned by our wallet in some sense. 
- I miss my `<Badge />` I thought it looked cool :-(

**Comment by geoknee** [comment]
Once the UI settles down a bit we should thin out some of the UI libraries / dependencies we (ok, I) have pulled in, especially if we use 1 or 0 components from them.

**Comment by tomclose** [comment]
I like the new data column too. Is there enough space to add a Payments column. We could use send/receive for data, and spent/earned for money.

**Comment by geoknee** [comment]
😆  payments column was removed 30 mins ago #1943

**Comment by snario** [comment]
> sent / received terminology collides with payment terminology. I send you money, you send me data. prefer uploaded / downloaded

fixed

> vertical alignment does a bit of a wave

fixed

> I miss my <Badge /> I thought it looked cool :-(

added back

> disconnected (bad) is a grey dot. finished (good) is a different grey dot

fixed

commit incoming

Screen Shot 2020-05-22 at 08 00 05

**Pull request merged**
