### PR TITLE
Remove comment capitalization rule

### PR DESCRIPTION
**Pull request by snario**
I think this rule sucks. Who's with me!? #546

### CODE REVIEW

**Comment by Alonski** [comment]
I like the rule 😭 
In English we type like this.
we don't type like this

**Comment by andrewgordstewart** [comment]
> I like the rule 😭
> In English we type like this.
> we don't type like this
> 
> but if everyone else wants to type like this I am ok with that :)

I see we've got a prescriptionist over here 😛

**Comment by snario** [comment]
I think it breaks some special rules that must be embedded in comments such as `/* tslint:disable */` and `/* webpackMode: 'eager' */`.

**Comment by andrewgordstewart** [comment]
If `{t|e}slint` can autofix, then anyone who's indifferent shouldn't care, and people who do care are satisfied.

Then again, @snario makes a good point about special rules

**Comment by Alonski** [comment]
@snario Those can be ignored.
https://eslint.org/docs/rules/capitalized-comments#ignorepattern

**Comment by tomclose** [comment]
I think it's simplest just to disable this. You can write with comments with capital letters if you want, but you don't have to. :)

**Pull request merged**
