### PR TITLE
Release 12-02-20

### PR DESCRIPTION
**Pull request by Alonski**

### CODE REVIEW

**Comment by kerzhner** [comment]
@Alonski unless you have objections, we should probably close this PR based on today's standup discussion

**Comment by Alonski** [comment]
@kerzhner I'll watch the recording tomorrow to catch up. Thanks!

**Comment by geoknee** [comment]
@alonski TLDR `deploy` got updated to a recent commit on master so should include the changes you wanted now.

**Comment by Alonski** [comment]
Great! Thanks @geoknee for the update

**Pull request closed without merging**
